import json
import pandas as pd

# Load the JSON generated by the scraper
with open('items_all.json', 'r', encoding='utf-8') as f:
    items = json.load(f)

# Prepare the data for WooCommerce
rows = []
for item in items:
    # WooCommerce expects images separated by commas in the 'Images' column
    images = ','.join(item.get('ImageLinks', []))
    rows.append({
        'Name': item.get('Name', ''),
        'Categories': item.get('Category', ''),
        'Regular price': item.get('Price', '').replace('€', '').replace(',', '').strip(),
        'Description': '',  # You can fill this if you have a description
        'Images': images,
        'SKU': item.get('ID', ''),
        'Stock': '',
        'Status': item.get('Status', ''),
        'Featured': item.get('Featured', ''),
        'Updated': item.get('Updated', ''),
    })

# Create the DataFrame and save the WooCommerce-compatible CSV
wc_df = pd.DataFrame(rows)
wc_df.to_csv('woocommerce_import.csv', index=False)

print(f"File 'woocommerce_import.csv' generated with {len(rows)} products ready to import into WooCommerce.")
